keep it simple

diff --git a/.svic321/bin/install b/.svic321/bin/install
--- a/.svic321/bin/install
+++ b/.svic321/bin/install
@@ -16,18 +16,19 @@ if git clone --bare git@github.com:svic321/dotfiles.git $HOME/.dotfiles; then \
         git clone --bare https://github.com/svic321/dotfiles.git $HOME/.dotfiles; \
     fi
 
+/usr/bin/git --git-dir=$HOME/.dotfiles/ --work-tree=$HOME checkout
 # Set up the alias for dotfiles
 # alias dotfiles='/usr/bin/git --git-dir=$HOME/.dotfiles/ --work-tree=$HOME' && \
-/usr/bin/git --git-dir=$HOME/.dotfiles/ --work-tree=$HOME config --local status.showUntrackedFiles no
+# /usr/bin/git --git-dir=$HOME/.dotfiles/ --work-tree=$HOME config --local status.showUntrackedFiles no
 
-# Attempt to check out dotfiles
-if ! /usr/bin/git --git-dir=$HOME/.dotfiles/ --work-tree=$HOME checkout; then
-  echo "Conflicting files detected. Backing them up and retrying..."
-  mkdir -p .dotfiles-backup && \
-  dotfiles checkout 2>&1 | egrep "\s+\." | awk {'print $1'} | \
-  xargs -I{} sh -c 'mkdir -p "$(dirname ".dotfiles-backup/{}")" && mv "{}" ".dotfiles-backup/{}"'
-  /usr/bin/git --git-dir=$HOME/.dotfiles/ --work-tree=$HOME checkout
-fi
+# # Attempt to check out dotfiles
+# if ! /usr/bin/git --git-dir=$HOME/.dotfiles/ --work-tree=$HOME checkout; then
+#   echo "Conflicting files detected. Backing them up and retrying..."
+#   mkdir -p .dotfiles-backup && \
+#   dotfiles checkout 2>&1 | egrep "\s+\." | awk {'print $1'} | \
+#   xargs -I{} sh -c 'mkdir -p "$(dirname ".dotfiles-backup/{}")" && mv "{}" ".dotfiles-backup/{}"'
+#   /usr/bin/git --git-dir=$HOME/.dotfiles/ --work-tree=$HOME checkout
+# fi
 # add custom git config
 git config --global include.path ~/.svic321/git/.gitconfig
 # use zsh plugins
